baseURL = "http://example.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"
theme = "hugograyscale"
title = "Hugo Grayscale Theme"
[Author]
email = "dco@runningstream.net"
name = "RunningStream"
[Social]
twitter = "stream_running"
[params]
description = "A port of the Grayscale theme to Hugo"
